const express = require("express");
const router = express.Router();
const getAnimalInformationData = require("../controller/fetchInforamtionData/getAnimalInformationData.js");
const getBreeds = require("../controller/fetchInforamtionData/getBreeds.js");
const getTypes = require("../controller/fetchInforamtionData/getTypes.js");
const authenticate = require("../controller/Auth/authenticate.js");
router.get("/getType", authenticate, getTypes);
router.post("/getBreed", authenticate, getBreeds);
router.post("/getAnimalInformation", authenticate, getAnimalInformationData);
module.exports = router;
