const express = require("express");
const router = express.Router();
const AnimalInformationData = require("../controller/fetchInforamtionData/AnimalInformationPage.js");
const BreedHandler = require("../controller/fetchInforamtionData/BreedHandler");
const TypeHandler = require("../controller/fetchInforamtionData/TypeHandler.js");
const authenticate = require("../controller/Auth/authenticate.js");
router.get("/getType", authenticate, TypeHandler);
router.post("/getBreed", authenticate, BreedHandler);
router.post("/getAnimalInformation", authenticate, AnimalInformationData);
module.exports = router;
